language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '10'
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
script:
  - commitlint-travis
  - yarn test --maxWorkers 4
